import json
import random

# List of words with meanings for vocabulary questions
vocab_data = [
    ("happy", "joyful", ["sad", "angry", "tired"]),
    ("sad", "sorrowful", ["happy", "joyful", "excited"]),
    ("big", "large", ["small", "tiny", "miniature"]),
    ("small", "tiny", ["big", "large", "huge"]),
    ("fast", "quick", ["slow", "sluggish", "lethargic"]),
    ("slow", "sluggish", ["fast", "quick", "rapid"]),
    ("hot", "warm", ["cold", "chilly", "freezing"]),
    ("cold", "chilly", ["hot", "warm", "boiling"]),
    ("good", "excellent", ["bad", "terrible", "awful"]),
    ("bad", "terrible", ["good", "excellent", "wonderful"]),
    ("new", "fresh", ["old", "ancient", "antique"]),
    ("old", "ancient", ["new", "fresh", "modern"]),
    ("rich", "wealthy", ["poor", "destitute", "impoverished"]),
    ("poor", "destitute", ["rich", "wealthy", "affluent"]),
    ("strong", "powerful", ["weak", "feeble", "fragile"]),
    ("weak", "feeble", ["strong", "powerful", "mighty"]),
    ("smart", "intelligent", ["dumb", "stupid", "ignorant"]),
    ("dumb", "stupid", ["smart", "intelligent", "clever"]),
    ("beautiful", "gorgeous", ["ugly", "hideous", "repulsive"]),
    ("ugly", "hideous", ["beautiful", "gorgeous", "attractive"]),
    ("clean", "spotless", ["dirty", "filthy", "grimy"]),
    ("dirty", "filthy", ["clean", "spotless", "immaculate"]),
    ("full", "replete", ["empty", "vacant", "void"]),
    ("empty", "vacant", ["full", "replete", "overflowing"]),
    ("hard", "difficult", ["easy", "simple", "effortless"]),
    ("easy", "simple", ["hard", "difficult", "challenging"]),
    ("high", "tall", ["low", "short", "diminutive"]),
    ("low", "short", ["high", "tall", "elevated"]),
    ("long", "extended", ["short", "brief", "concise"]),
    ("short", "brief", ["long", "extended", "prolonged"]),
    ("right", "correct", ["wrong", "incorrect", "erroneous"]),
    ("wrong", "incorrect", ["right", "correct", "accurate"]),
    ("true", "accurate", ["false", "untrue", "deceptive"]),
    ("false", "untrue", ["true", "accurate", "genuine"]),
    ("light", "bright", ["dark", "gloomy", "dim"]),
    ("dark", "gloomy", ["light", "bright", "luminous"]),
    ("loud", "noisy", ["quiet", "silent", "muted"]),
    ("quiet", "silent", ["loud", "noisy", "boisterous"]),
    ("wet", "moist", ["dry", "arid", "parched"]),
    ("dry", "arid", ["wet", "moist", "soggy"]),
    ("sweet", "sugary", ["sour", "tart", "acidic"]),
    ("sour", "tart", ["sweet", "sugary", "delicious"]),
    ("bitter", "acrid", ["sweet", "sugary", "palatable"]),
    ("salty", "briny", ["sweet", "sugary", "bland"]),
    ("ephemeral", "transient", ["permanent", "eternal", "lasting"]),
    ("ubiquitous", "omnipresent", ["rare", "scarce", "uncommon"]),
    ("gregarious", "sociable", ["shy", "introverted", "reserved"]),
    ("laconic", "concise", ["verbose", "wordy", "loquacious"]),
    ("pragmatic", "practical", ["idealistic", "theoretical", "utopian"]),
    ("candid", "forthright", ["deceptive", "dishonest", "insincere"]),
    ("altruistic", "selfless", ["selfish", "egotistical", "greedy"]),
    ("stoic", "impassive", ["emotional", "passionate", "expressive"]),
    ("ebullient", "exuberant", ["subdued", "restrained", "melancholy"]),
    ("quixotic", "impractical", ["practical", "realistic", "sensible"]),
    ("sagacious", "wise", ["foolish", "stupid", "ignorant"]),
    ("obtuse", "dense", ["sharp", "keen", "perceptive"]),
    ("fastidious", "meticulous", ["careless", "sloppy", "negligent"]),
    ("perfunctory", "cursory", ["thorough", "detailed", "comprehensive"]),
    ("insidious", "treacherous", ["obvious", "evident", "apparent"]),
    ("magnanimous", "generous", ["petty", "stingy", "selfish"]),
    ("pedantic", "didactic", ["simple", "straightforward", "uncomplicated"]),
    ("esoteric", "arcane", ["common", "familiar", "mundane"]),
    ("sycophantic", "obsequious", ["independent", "autonomous", "self-reliant"]),
    ("taciturn", "reticent", ["talkative", "garrulous", "loquacious"]),
    ("voracious", "ravenous", ["satiated", "full", "content"]),
    ("nefarious", "wicked", ["virtuous", "moral", "righteous"]),
    ("pulchritudinous", "beautiful", ["ugly", "hideous", "repulsive"]),
    ("sesquipedalian", "long-winded", ["concise", "brief", "succinct"]),
    ("perspicacious", "insightful", ["oblivious", "unaware", "ignorant"]),
    ("mellifluous", "sweet-sounding", ["harsh", "discordant", "grating"]),
    ("quintessential", "archetypal", ["untypical", "atypical", "aberrant"]),
    ("euphemistic", "indirect", ["direct", "blunt", "forthright"]),
    ("ostentatious", "showy", ["modest", "unassuming", "humble"]),
    ("recalcitrant", "stubborn", ["compliant", "obedient", "submissive"]),
    ("sanguine", "optimistic", ["pessimistic", "gloomy", "despondent"]),
    ("tendentious", "biased", ["impartial", "neutral", "objective"]),
    ("unctuous", "oily", ["genuine", "sincere", "authentic"]),
    ("vicissitudinous", "variable", ["constant", "steady", "unchanging"]),
    ("winsome", "charming", ["repulsive", "unattractive", "offensive"]),
    ("zealous", "ardent", ["apathetic", "indifferent", "uninterested"]),
    ("aberrant", "deviant", ["normal", "standard", "conventional"]),
    ("bellicose", "warlike", ["peaceful", "pacific", "conciliatory"]),
    ("cogent", "convincing", ["unconvincing", "weak", "flimsy"]),
    ("diatribe", "tirade", ["praise", "commendation", "eulogy"]),
    ("effulgent", "radiant", ["dull", "dim", "lackluster"]),
    ("farcical", "ludicrous", ["serious", "grave", "solemn"]),
    ("garrulous", "talkative", ["taciturn", "reticent", "quiet"]),
    ("halcyon", "peaceful", ["turbulent", "stormy", "chaotic"]),
    ("iconoclastic", "heretical", ["orthodox", "conventional", "traditional"]),
    ("jejune", "insipid", ["interesting", "engaging", "stimulating"]),
    ("kith", "friends", ["strangers", "acquaintances", "foes"]),
    ("limpid", "clear", ["murky", "opaque", "cloudy"]),
    ("mendacious", "lying", ["truthful", "honest", "veracious"]),
    ("noisome", "offensive", ["pleasant", "agreeable", "delightful"]),
    ("obfuscate", "confuse", ["clarify", "explain", "elucidate"]),
    ("pallid", "pale", ["ruddy", "flushed", "rosy"]),
    ("quiescent", "inactive", ["active", "dynamic", "energetic"]),
    ("rancorous", "bitter", ["amiable", "friendly", "cordial"]),
    ("sardonic", "sarcastic", ["sincere", "genuine", "earnest"]),
    ("turgid", "swollen", ["shrunken", "contracted", "deflated"]),
    ("ubiquitous", "everywhere", ["nowhere", "scarce", "rare"]),
    ("vacuous", "empty", ["full", " replete", "overflowing"]),
    ("wily", "cunning", ["naive", "innocent", "gullible"]),
    ("xenophobic", "fearful of strangers", ["welcoming", "hospitable", "open"]),
    ("yokel", "rustic", ["sophisticate", "cosmopolitan", "urbane"]),
    ("zephyr", "gentle breeze", ["gale", "storm", "tempest"]),
    ("abject", "wretched", ["exalted", "noble", "elevated"]),
    ("bilious", "irritable", ["calm", "placid", "serene"]),
    ("cabal", "conspiracy", ["alliance", "partnership", "coalition"]),
    ("droll", "amusing", ["dull", "boring", "tedious"]),
    ("effervescent", "bubbly", ["flat", "still", "stagnant"]),
    ("foppish", "dandyish", ["plain", "simple", "unadorned"]),
    ("gossamer", "delicate", ["coarse", "rough", "sturdy"]),
    ("hirsute", "hairy", ["bald", "hairless", "smooth"]),
    ("ignominious", "humiliating", ["glorious", "honorable", "praiseworthy"]),
    ("jocular", "joking", ["serious", "grave", "somber"]),
    ("kaleidoscopic", "multicolored", ["monochromatic", "uniform", "homogeneous"]),
    ("languid", "lethargic", ["energetic", "vigorous", "lively"]),
    ("misanthropic", "hating mankind", ["philanthropic", "benevolent", "humanitarian"]),
    ("nugatory", "worthless", ["valuable", "precious", "invaluable"]),
    ("obstreperous", "noisy", ["quiet", "silent", "subdued"]),
    ("piquant", "spicy", ["bland", "tasteless", "insipid"]),
    ("quagmire", "swamp", ["dry land", "desert", "prairie"]),
    ("recondite", "obscure", ["familiar", "well-known", "common"]),
    ("soporific", "sleep-inducing", ["stimulating", "awakening", "rousing"]),
    ("tremulous", "trembling", ["steady", "firm", "stable"]),
    ("umbrage", "offense", ["pleasure", "delight", "satisfaction"]),
    ("vapid", "dull", ["interesting", "engaging", "stimulating"]),
    ("wraith", "ghost", ["living person", "corporeal being", "tangible entity"]),
    ("xanthic", "yellow", ["blue", "red", "green"]),
    ("yammer", "whine", ["praise", "commend", "applaud"]),
    ("zest", "enthusiasm", ["apathy", "indifference", "disinterest"]),
    ("acerbic", "sharp", ["mild", "gentle", "soft"]),
    ("blithe", "carefree", ["careful", "cautious", "worried"]),
    ("cynical", "distrustful", ["trusting", "credulous", "naive"]),
    ("dulcet", "sweet", ["harsh", "discordant", "bitter"]),
    ("ebullient", "enthusiastic", ["subdued", "restrained", "melancholy"]),
    ("facetious", "joking", ["serious", "grave", "somber"]),
    ("gauche", "awkward", ["graceful", "elegant", "polished"]),
    ("histrionic", "dramatic", ["calm", "composed", "restrained"]),
    ("impecunious", "penniless", ["wealthy", "rich", "affluent"]),
    ("jejune", "dull", ["interesting", "engaging", "stimulating"]),
    ("knotty", "complicated", ["simple", "easy", "straightforward"]),
    ("lurid", "sensational", ["mild", "subdued", "restrained"]),
    ("mellifluous", "melodious", ["harsh", "discordant", "grating"]),
    ("nadir", "lowest point", ["zenith", "peak", "summit"]),
    ("obdurate", "stubborn", ["flexible", "yielding", "compliant"]),
    ("palliate", "ease", ["worsen", "aggravate", "exacerbate"]),
    ("querulous", "complaining", ["content", "satisfied", "pleased"]),
    ("rhapsodic", "ecstatic", ["dispirited", "dejected", "gloomy"]),
    ("sardonic", "mocking", ["sincere", "genuine", "earnest"]),
    ("tacit", "implied", ["explicit", "stated", "declared"]),
    ("unctuous", "smarmy", ["genuine", "sincere", "authentic"]),
    ("venerable", "respected", ["disrespected", "scorned", "despised"]),
    ("winsome", "attractive", ["repulsive", "unattractive", "offensive"]),
    ("xenon", "gas", ["solid", "liquid", "plasma"]),  # wait, not vocab
    # I have about 150, need more
    ("abate", "diminish", ["increase", "augment", "intensify"]),
    ("belligerent", "hostile", ["peaceful", "amicable", "conciliatory"]),
    ("cajole", "coax", ["force", "compel", "coerce"]),
    ("deprecate", "disapprove", ["approve", "commend", "praise"]),
    ("enervate", "weaken", ["strengthen", "fortify", "invigorate"]),
    ("foment", "instigate", ["suppress", "quell", "pacify"]),
    ("gainsay", "deny", ["affirm", "confirm", "acknowledge"]),
    ("harangue", "rant", ["whisper", "murmur", "mumble"]),
    ("inchoate", "undeveloped", ["developed", "mature", "complete"]),
    ("jingoistic", "nationalistic", ["cosmopolitan", "international", "global"]),
    ("kudos", "praise", ["criticism", "condemnation", "censure"]),
    ("lethargic", "sluggish", ["energetic", "vigorous", "lively"]),
    ("malinger", "feign illness", ["work hard", "labor", "toil"]),
    ("neophyte", "beginner", ["expert", "veteran", "master"]),
    ("obviate", "prevent", ["cause", "provoke", "induce"]),
    ("paean", "song of praise", ["dirge", "lament", "elegy"]),
    ("quibble", "argue over triviality", ["agree", "concur", "assent"]),
    ("reprobate", "scoundrel", ["saint", "angel", "virtuous person"]),
    ("satiate", "satisfy fully", ["starve", "deprive", "deny"]),
    ("temporize", "delay", ["hurry", "rush", "accelerate"]),
    ("usurp", "seize", ["relinquish", "surrender", "yield"]),
    ("vitiate", "impair", ["improve", "enhance", "better"]),
    ("wanton", "reckless", ["careful", "prudent", "cautious"]),
    ("yoke", "join", ["separate", "divide", "disjoin"]),
    ("zenith", "peak", ["nadir", "bottom", "low point"]),
    ("abase", "humiliate", ["elevate", "exalt", "honor"]),
    ("brusque", "abrupt", ["polite", "courteous", "gracious"]),
    ("chicanery", "trickery", ["honesty", "integrity", "sincerity"]),
    ("dilettante", "amateur", ["professional", "expert", "specialist"]),
    ("epitome", "perfect example", ["poor example", "atypical", "unrepresentative"]),
    ("feckless", "irresponsible", ["responsible", "reliable", "dependable"]),
    ("germane", "relevant", ["irrelevant", "inapplicable", "unrelated"]),
    ("hew", "chop", ["build", "construct", "assemble"]),
    ("immutable", "unchanging", ["changeable", "mutable", "variable"]),
    ("juxtapose", "place side by side", ["separate", "divide", "isolate"]),
    ("kith and kin", "friends and family", ["strangers", "outsiders", "aliens"]),
    ("lacerate", "tear", ["heal", "mend", "repair"]),
    ("maunder", "ramble", ["focus", "concentrate", "direct"]),
    ("nadir", "lowest point", ["zenith", "peak", "summit"]),
    ("obfuscate", "confuse", ["clarify", "explain", "elucidate"]),
    ("palliate", "alleviate", ["worsen", "aggravate", "exacerbate"]),
    ("quiescent", "dormant", ["active", "dynamic", "energetic"]),
    ("rife", "abundant", ["scarce", "rare", "deficient"]),
    ("sanguine", "optimistic", ["pessimistic", "gloomy", "despondent"]),
    ("tendentious", "biased", ["impartial", "neutral", "objective"]),
    ("usury", "excessive interest", ["fair rate", "reasonable charge", "modest fee"]),
    ("verisimilitude", "appearance of truth", ["falsity", "deception", "illusion"]),
    ("wily", "sly", ["naive", "innocent", "gullible"]),
    ("yore", "long ago", ["now", "present", "future"]),
    ("zany", "crazy", ["sane", "rational", "reasonable"]),
]

# Shuffle to randomize
random.shuffle(vocab_data)

# Generate questions
questions = []
for i, (word, correct, wrongs) in enumerate(vocab_data[:200]):  # take 200
    lesson = (i // 20) + 1
    q_num = (i % 20) + 1
    question_text = f"What does '{word}' mean?"
    choices = [correct] + wrongs
    random.shuffle(choices)
    answer_index = choices.index(correct)
    if lesson <= 3:
        difficulty = "Easy"
    elif lesson <= 7:
        difficulty = "Medium"
    else:
        difficulty = "Hard"
    q = {
        "id": f"vocabulary_lesson{lesson}_q{q_num}",
        "type": "multiple-choice",
        "question": question_text,
        "choices": choices,
        "answer": answer_index,
        "explanation": f"{word} means {correct}.",
        "difficulty": difficulty
    }
    questions.append(q)

# Group by lesson
vocabulary = {}
for q in questions:
    lesson = int(q['id'].split('_')[1][6:])  # lesson number
    if lesson not in vocabulary:
        vocabulary[lesson] = []
    vocabulary[lesson].append(q)

# Sort lessons
vocabulary = {str(k): v for k, v in sorted(vocabulary.items())}

# Output JSON
with open('vocabulary_output.json', 'w') as f:
    json.dump({"vocabulary": vocabulary}, f, indent=2)